#The sacred archives
quote_list = [
        'Ms woolpy woolps asses', 'Im addict to porn',
        'How do I put a stick in a donut hole', 'I like Dora the explorer',
        'Did you smack them booties', 'Im sexier than everybody',
        'The uterus open up so wide it explodes',
        'Oh the urethra spills liquid that causes fire',
        'My left dick dropped. 5 points today', 'Yes porn',
        'Jimbo porn eats cor', 'Dont be a maozodong', 'I made porn',
        'Africa is coming', 'I wipe my butt with a potato chip', 'Jaime thick',
        'Whose going trickle treating', 'drink methane', 'drick cute girls',
        'eat vegans', 'I dont speak aztec',
        'take a suction cup and suck it up', 'eat my computer',
        'uncle sams too whit for me', 'Amazon is my third party butthole',
        'Im a fan of pornicon mixed manga', 'Moist', 'Thick',
        'Drink some corona beer', 'Santa is meat', 'Wieners',
        'Hey zuckerberg suck my dick', 'Porn cats', 'Yes bois we got thick',
        'Boobs', 'I won', 'Im god', 'Mating season', 'You k for Kellogg',
        'I eat ass', 'Pedometer', 'There thick family guy', 'Shut up', 'Porn',
        'Yes penis', 'How do cats give birth', 'I gave birth to fish',
        'The thickness of my thighs', 'Juicy tender', 'Women do wear diapers',
        'Chandelier take sex Ed', 'You serebullem', 'Invest in marijuana',
        'Prepare for war', 'Eat my rawmin', 'Chicks are cuter than Jimbo',
        'Nuggets on my nuts', 'I love porn', 'Dab',
        'We all know chandelier loves porn', 'Hentai 2.0', 'Communism',
        'Ask yourself does this theory match jays reasoning', 'Boost up',
        'God bless Taiwan', 'I love my country', 'Go China',
        'I was the one that predicted inflation', 'I cant wait for inflation',
        'Women these days there so complicated', 'Hitlerism',
        'Who cares about the Native American',
        'You look dum against investopedia', 'You need a sensai',
        'Why bring workers to work', 'Join the wang',
        'Give me Adam back from the garden',
        'I sterilization of economy is dum',
        'Why does ocasio cortex look cute', 'Death to America', 'Dont boil me',
        'Iraq lobster', 'When thickkkk', 'I got bullied by a communist',
        'iOS wonder if someone ever pooped out metal', 'She man',
        'Vegetales should mix with sausage party',
        'Bra I cant wait tell the depression and recession and crash',
        'Jeff bezo for president 2022 son', 'Get ready for combat', 'Ja nuts',
        'Donut and wiener', 'Plug a hole',
        'Its not about plugging and chugging', 'Im watching porn',
        'Jaime looks foolish defying an economist', '2balls and a curve',
        'Smoke a bong', 'Im a virgin', 'Prostitution',
        'George Washington is a communist', 'Im technically challenged',
        'Is spongebob considered an anime', 'I play farm simulator',
        'Thick chick', 'I speak of no language', 'Eat jemima',
        'Drink coconut cocktail', 'Horny is good', 'I well squash you midget',
        'Suck cocks', 'Jesus was gay for eating his creations',
        'Im a authoritarianism', 'You whit brain', 'Your a fool',
        'Eat bok Choi', 'You pedo', 'I cant hear Im old', 'Your a  simpology',
        'I produced cat woman', 'B km km mnuchin', 'Breast feed yourself',
        'Eat titts', 'Hit ballz boi', 'Eat teenage turtle',
        'I have 3  testicles', 'God bless oil', 'Fuck thighs', 'Thick boy',
        'Fuck the cheerleaders', 'Get them booties',
        'Cancer is treatable with nukes', 'Horny is good',
        'I well steal your oxygen', 'Want bigger ballz', 'Mao so dong',
        'Tell that to El Paso your freakin tacos', 'Ill rob you', 'Cock you',
        'I love posting foot pics', 'Thong me up', 'Smoke a bong',
        'Bisexual toys', 'I love bisexual islam', 'N', 'I watch porn',
        'I eat children', 'Your next Ill eat your brains', 'You look stupid',
        'Poop', 'Juicy', 'Noobs are boobs', 'The communist are coming',
        'Come cook with your local crakpot', 'McDonalds is mine', 'Reichtag',
        'Alien are everywhere', 'Fight me', 'Belly flop on top of you',
        'Remember jay', 'Gas up', 'Ethanol is drinkable', 'I drill for porn',
        'You have hentai addicting', 'Vote vegetarian',
        'I usually read thick thighs', 'Im watching rich Asians',
        'Eat cadmium', 'You librochi', 'I plug hoes', 'Drink figi water',
        'Dont drink poop', 'I need ballz', 'Three thongs in one cup',
        'Threesomes with the whale',
        'Hey its your local meth head deliverying dopes',
        'Join the support for thick thighs', 'I love you chandelier',
        'Yes dont eat kids', 'Eat whales'
    ]